version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: hookd
      POSTGRES_PASSWORD: hookd
      POSTGRES_DB: hookd_tracker
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: app
      FLASK_DEBUG: 1
      DATABASE_URL: postgresql://hookd:hookd@db:5432/hookd_tracker
    depends_on:
      - db
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - WDS_SOCKET_PORT=0
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true

volumes:
  postgres_data:
