"""make accounts creator_id nullable

Revision ID: b6bb1b7c13f2
Revises: ad4ee1142cad
Create Date: 2026-03-19 06:15:37.230589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6bb1b7c13f2'
down_revision = 'ad4ee1142cad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.alter_column('creator_id',
               existing_type=sa.BIGINT(),
               nullable=True)

    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.alter_column('company_id',
               existing_type=sa.BIGINT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.alter_column('company_id',
               existing_type=sa.BIGINT(),
               nullable=False)

    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.alter_column('creator_id',
               existing_type=sa.BIGINT(),
               nullable=False)

    # ### end Alembic commands ###
